server:
  port: ${BPD_RANKING_PROCESSOR_PORT:8080}

spring:
  application:
    name: "@project.parent.artifactId@"
    version: "@project.version@"

info:
  build:
    artifact: "@project.parent.artifactId@"
    name: "@project.parent.artifactId@"
    description: "@project.description@"
    version: "@project.version@"

error-manager:
  enabled: true

meda:
  core:
    sessioncontext:
      enabled: false

logging:
  level:
    it.gov.pagopa.bpd.ranking_processor: ${LOG_LEVEL_BPD_RANKING_PROCESSOR:DEBUG}
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE