apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpdmsrankingprocessor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bpdmsrankingprocessor
  template:
    metadata:
      labels:
        app: bpdmsrankingprocessor
    spec:
      containers:
        - name: bpdmsrankingprocessor
          image: cstarregistry.azurecr.io/bpdmsrankingprocessor
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: postgres-credentials
            - configMapRef:
                name: eventhub-logging
            - configMapRef:
                name: bpdmsrankingprocessor
            - configMapRef:
                name: rest-client
            - configMapRef:
                name: jvm
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 30
          imagePullPolicy: Always #TODO: remove me
      hostAliases:
        - hostnames:
            - bpd-hub-dev.servicebus.windows.net
          ip: 10.70.5.9
