apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpdmsrankingprocessor
spec:
  replicas: 12
  selector:
    matchLabels:
      app: bpdmsrankingprocessor
  template:
    metadata:
      labels:
        app: bpdmsrankingprocessor
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: bpdmsrankingprocessor
          image: cstaruacr.azurecr.io/bpdmsrankingprocessor
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: postgres-credentials
            - secretRef:
                name: application-insights
            - configMapRef:
                name: eventhub-logging
            - configMapRef:
                name: bpdmsrankingprocessor
            - configMapRef:
                name: rest-client
            - configMapRef:
                name: jvm
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 30
            imagePullPolicy: Always

